### ISSUE TITLE
Error processing transaction request: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by yakotaki** [web3j/sample-project-gradle#4]
Hello, I'm running client
geth --rpcapi personal,db,eth,net,web3 --rpc --rinkeby

server answers:  instance=Geth/v1.7.3-stable/linux-amd64/go1.9.4...
importing blocks, no problem.

I fed my account "https://rinkeby.etherscan.io/address/0x03fb8e3666ee5dcc07fc74c85d26f0fd952e39e1"

But every time I'm trying to run sample.java i'm getting this error:

Connected to Ethereum client version: Geth/v1.7.3-stable/linux-amd64/go1.9.4
Credentials loaded
Sending 1 Wei (0.000000000000000001 Ether)
Exception in thread "main" java.lang.RuntimeException: Error processing transaction request: insufficient funds for gas * price + value
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:67)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:51)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:70)
	at org.web3j.tx.Transfer.send(Transfer.java:65)
	at org.web3j.tx.Transfer.send(Transfer.java:49)
	at org.web3j.tx.Transfer.lambda$sendFunds$20(Transfer.java:76)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at org.web3j.sample.Application.run(Application.java:81)
	at org.web3j.sample.Application.main(Application.java:55)

**Comment by Kuppa** [comment]
Make sure check that your provided address has enough ethers to send or not. I also ran into the same issue and later I found that there are no ethers with my address. So then later I have added some test ethers to my address and now I am able to send ethers from one address to another without any problem.

**Comment by iikirilov** [comment]
@yakotaki you need to get some ether. You can do this from a rinkeby faucet. (google it)
